# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be9a1f5291757359df1a375019d5f668a620d81d432e7541f34bce4d0d1c81e0678e86d2bc0fbd5d440b2e5f8cd6a761eacfd45e475136e20f402f431aa438ee

test:
  secret_key_base: 6d37655de16232127e8d3453976ba5385911417fa739f1579aa5c4bd5c9ca15f83672ae947b9391456425ee0ac92114b20a40e386379982d4e22e782bb9d30d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
